package GardenApplication1;

import java.util.ArrayList;

public class Garden {

  private  ArrayList<Plant> plants;


 /// autogenerated constructor here

    public Garden() {
        this.plants = new ArrayList<>();
    }


    public void addPlant(Plant plant) {
        plants.add(plant);
    }


    public void waterGarden(double amount) {
        System.out.println("watering with "+ (int)amount);
        int thirstyPlants = 0;

        //ak je v plants plant, tak ho vyberie a aplikuje
        //a ak nesplni podmienku tak vyberie dalsi
        //nie je to ohranicene
        //pojde az kym neprejde na posledny plant


        for (Plant plant: plants) {
            if (plant.needsWater()) {
                thirstyPlants++;
            }
        }

        if (thirstyPlants > 0) {
            double waterPerPlant = amount / thirstyPlants;

            for (Plant plant: plants) {
                if (plant.needsWater()) {
                    plant.waterAbsorbed(waterPerPlant);
                }
            }

        }

        showGarden();

    }

    public void showGarden() {
        for (Plant plant: plants) {
            if (plant.needsWater()) {
                System.out.println("this "+ plant.color+ " " +plant.getClass().getSimpleName()+ " wants to drink" );
            } else {
                System.out.println("The " + plant.color + " " + plant.getClass().getSimpleName() + " is Allrighty.. no water needed");
            }
        }
    }



}
