package GardenApplication1;

public class Plant {

    //initiating variables coloro and watero
    String color;
    double waterAmount;

    // here is CONSTRUCTOR
    public Plant(String color) {     // this was autogenerated
        this.color = color;          // this was autogenerated
        this.waterAmount =0;         // this was not
    }

    public boolean needsWater(){
        return false;
    }

    public void waterAbsorbed(double amount) {
    }

}
